### ISSUE TITLE
Roadmap: What's next

### ISSUE THREAD

**Issue by coolaj86** [msharp9/RecRoom#2]
So, we need to have a plan:
- [ ] Make a checklist of next steps
- [ ] Click the edit button on this very issue
- [ ] Replace my bogus list with your list
- [ ] Collaborate and make it happen

**Comment by msharp9** [comment]
@coolaj86: So this is what I was thinking:
- [x] Create front page with 'challenge friend' and 'create tournament' buttons (in progress)
- [x] Create tournament form
- [ ] Save tournament information into a database (was thinking MongoDB or a simple JSON flat file)
- [ ] Display list of currently open and in progress tournaments on front page
- [ ] Create display to show bracket and allow user interface to update with wins/losses/apply challenge friend code to open seats in open tournaments

Were you planning on going to the Learners JavaScript meet-up again this Saturday?  If so I will attempt to finish the first two by then.  I think checklist items 3 and 4 would be good to try and work on then.
